### ISSUE TITLE
Create press@... email contact

### ISSUE THREAD

**Issue by eyledog** [GwilymNewton/makers-4-the-nhs-planning#4]
Grant access to Local PR Project Owner

**Comment by GwilymNewton** [comment]
I can do this, I need a gmail end point to attach it to. Once you have a 

makers4thenhs_press@gmail.com setup, I will take it form there.

**Comment by GwilymNewton** [comment]
@elliepaine91 can you handle that

**Comment by GwilymNewton** [comment]
Done 

![](https://files.slack.com/files-pri/T010P21B97T-F012500HG4A/screenshot_2020-04-20_at_10.39.34.png)

**Comment by GwilymNewton** [comment]
press@makers3thenhs.com

& sponsor@makers4thenhs.com
